name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 150.136.46.27
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          echo "${{ steps.extract_branch.outputs.branch }}"
          if [ ${{ steps.extract_branch.outputs.branch }} = "main" ]; then
            cd /home/ubuntu/rancher-services/perfectportion/api.perfectportion.tech
          elif [ ${{ steps.extract_branch.outputs.branch }} = "staging" ] ; then
            cd /home/ubuntu/rancher-services/perfectportion/stagingapi.perfectportion.tech
          else
            exit 0
          fi
          echo "$PWD"
          git pull origin ${{ steps.extract_branch.outputs.branch }} --allow-unrelated-histories
